### ISSUE TITLE
Compatibility with Arcam ST60

### ISSUE THREAD

**Issue by lealoureiro** [elupus/arcam_fmj#26]
Hello,

I would like check if this library is also compatible with Arcam ST60 DAC/Streamer?
If not maybe I can try collaborate and extend or maybe create a new lib all together.  What you think?

I'm planning to acquire one and integrate it with HA. 

Regards,
Leandro

**Comment by lealoureiro** [comment]
Cool!

Is there any docs regarding the module architecture? For example, what are functions of server, client and state file?

**Comment by elupus** [comment]
Server is a dummy server for testing
Client is the low lever communication handler
State is the manager of trying to reflect/affect the state of the device

**Comment by lealoureiro** [comment]
I tried recently to just get the state of the ST60 without any code changes and seems to work:

```console
arcam-fmj state --host 192.168.x.x
unexpected str byte b'\x00'
unexpected str byte b'\x00'
unexpected str byte b'\x00'
unexpected str byte b'\x00'
unexpected str byte b'\x00'
unexpected str byte b'\x00'
unexpected str byte b'\x00'
unexpected str byte b'\x00'
unexpected str byte b'\x00'
unexpected str byte b'\x00'
unexpected str byte b'\x00'
unexpected str byte b'\x00'
unexpected str byte b'\x00'
unexpected str byte b'\x00'
unexpected str byte b'\x00'
unexpected str byte b'\x00'
unexpected str byte b'\x00'
unexpected str byte b'\x00'
unexpected str byte b'\x00'
unexpected str byte b'\x00'
unexpected str byte b'\x00'
unexpected str byte b'\x00'
unexpected str byte b'\x00'
unexpected str byte b'\x00'
unexpected str byte b'\x00'
unexpected str byte b'\x00'
unexpected str byte b'\x00'
unexpected str byte b'\x00'
State ({'POWER': True, 'VOLUME': 26, 'SOURCE': None, 'MUTE': False, 'MENU': None, 'INCOMING_AUDIO_FORMAT': (None, None), 'DECODE_MODE_2CH': None, 'DECODE_MODE_MCH': None, 'DAB_STATION': None, 'DLS_PDT': None, 'RDS_INFORMATION': None, 'TUNER_PRESET': None, 'PRESET_DETAIL': {}}) Amx ({'Device-SDKClass': 'Amplifier', 'Device-Make': 'ARCAM', 'Device-Model': 'ST60', 'Device-Revision': '0.72.0'})
```

Is a bit strange that is complaining about the **unexpected str byte b'\x00'**, i see in ST60 spec that it should also start `St (Start transmission): 0x21 ‘!’`

Does this also happen with other already supported devices?

However I can already without any code changes do turn off/on the device with following command:
```console
arcam-fmj client --host 192.168.178.201 --command 0x00 --data 0x00
arcam-fmj client --host 192.168.178.201 --command 0x00 --data 0x01
```

In home-assistant does not work properly yet.

**Comment by elupus** [comment]
The likely cause is in: https://github.com/elupus/arcam_fmj/blob/f06ae9677917904e175f18b7bce61fb5eb16cd85/src/arcam/fmj/__init__.py#L839

**Comment by elupus** [comment]
Please run the state request with --verbose on. Might tell us the cause of those logs.

**Comment by lealoureiro** [comment]
> Owner

What is the exact command to run with verbose? (Sorry I'm still a bit new to python :( )

**Comment by elupus** [comment]
`arcam-fmj --verbose state --host 192.168.178.201`

**Comment by lealoureiro** [comment]
I create a sample test client in python and seems the ST60 sends 2 0x00 after every response, don't know why, does not seem to be in the docs:


```python
import socket

HOST = "192.168.178.201"  # The server's hostname or IP address
PORT = 50000  # The port used by the server


command = b'\x21\x01\x00\x01\x00\x0d'

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.connect((HOST, PORT))
    s.sendall(command)
    data = s.recv(7)
    print(''.join('0x%02x '%i for i in data))

    while(True):
        data = s.recv(1)
        print(f"Received {data}")
````

output:
```console
python test_client.py                                                                                                                                                                              main 00:45:56
0x21 0x01 0x00 0x00 0x01 0x00 0x0d
Received b'\x00'
Received b'\x00'
```

Any added some constants for ST60 and now I can control the power: https://github.com/lealoureiro/arcam_fmj/commit/2bb0e23986510a591a61670882e5238b7792667e

**Comment by elupus** [comment]
Nice. we should change read_delimited to ignore all null (0) bytes before it gets too the start byte.
