### ISSUE TITLE
Support for Lexicon RX/MC series

### ISSUE THREAD

**Issue by Robotron80** [elupus/arcam_fmj#31]
Hey there,

I‘m using your library within the Home Assistant integration. However I‘ve got a Lexicon MC10 AVR, which is basically an AV860. Most of the commands are working, but there are some issues with source switching and upmixing modes.

Could you add support for those Lexicon models too? I‘m wondering if I could help somehow or could do it myself by editing the AV860 integration?

**Comment by elupus** [comment]
You likely need to make sure the device get detected as an AV860 or similar in _update_amxduet() in state.py, otherwise mappings will not match.
