### ISSUE TITLE
RC5 power on command not working

### ISSUE THREAD

**Issue by evanugarte** [elupus/arcam_fmj#4]
I am currently testing the project with an Arcam SA10 Integrated Amplifier. While the models are different, the command to turn on the device is the same as the AVR450 which this project was intended for.

as per the [SA-10 Datasheet](https://www.arcam.co.uk/ugc/tor/SA10/Custom%20Installation%20Notes/SH277E_RS232_SA10_SA20_B.pdf):
![datasheet](https://user-images.githubusercontent.com/36345325/129986276-26ede3e6-912f-4d0b-a462-8a303fff8ada.png)

All other RC5 commands when tested work but not the power on. I was able to turn the power on the device by referencing this section of the datasheet:

![Screenshot from 2021-08-18 16-52-04](https://user-images.githubusercontent.com/36345325/129986495-d6d8503d-51df-4b29-b695-ba838821bf29.png)

related python code `data` being defined in [`src/arcam/fmj/__init__.py:723`](https://github.com/elupus/arcam_fmj/blob/5b03ef6705748177f4403c8dd3afc10077214a57/src/arcam/fmj/__init__.py#L723):
```py
data = bytes([
    0x21,
    0x01,
    0x00,
    0x01,
    0x01,
    0x0D
])
```

Does anyone know if the RC5 power on command works for their devices?

**Comment by elupus** [comment]
I think it works for mine. I need to turn on zone two though otherwise my whole amp shuts down.

I don't remember if I tested that command.

**Comment by evanugarte** [comment]
Thanks for letting me know, what if the state functions had an optional parameter for using RC5?

for example in [`src/arcam/fmj/state.py:246`](https://github.com/elupus/arcam_fmj/blob/5b03ef6705748177f4403c8dd3afc10077214a57/src/arcam/fmj/state.py#L246)
```py
async def set_source(self, src: SourceCodes, use_rc5=True) -> None:
    if use_rc5:
        command = self.get_rc5code(RC5CODE_SOURCE, src)
        await self._client.request(
            self._zn, CommandCodes.SIMULATE_RC5_IR_COMMAND, command)
    else:
        await self._client.request(
            self._zn, CommandCodes.CURRENT_SOURCE, bytes([src]))
```

If this sounds feasible I'd be happy to build this functionality out with tests.

**Comment by elupus** [comment]
current source sadly does not support setting a value (on my system nor on any of the other currently supported). Neither does setting power state.

But yes i will accept a pull request for adding support for the SA-10 / SA-20. The model name should already be available from the AMX Duet string it now reads out.

**Comment by elupus** [comment]
Could you please first correct the RC5 codes and the lookup tables?

**Comment by evanugarte** [comment]
> current source sadly does not support setting a value (on my system nor on any of the other currently supported). Neither does setting power state.

The above code works for me on the SA10. I had built out some other functions to use non RC5 commands [here](https://github.com/evanugarte/arcam_fmj/pull/1/files#diff-c8d4365d33c029387da1fd395f60911c120fdede2c4d9739c78514a2e6982cc3R200) (albeit a rough draft).

> Could you please first correct the RC5 codes and the lookup tables?

The RC5 codes on the SA10 model appear to match what's defined in [`src/arcam/fmj/__init__.py`](https://github.com/elupus/arcam_fmj/blob/master/src/arcam/fmj/__init__.py)

**Comment by elupus** [comment]
Right. But you need to setup a model series. Otherwise the list of source's will be wrong. It should add a model series to ApiModel. Then in state.py (https://github.com/elupus/arcam_fmj/blob/5b03ef6705748177f4403c8dd3afc10077214a57/src/arcam/fmj/state.py#L341) set that when a supported modelname is detected.
Then add new sections to the source list (https://github.com/elupus/arcam_fmj/blob/5b03ef6705748177f4403c8dd3afc10077214a57/src/arcam/fmj/__init__.py#L328) and the power list (https://github.com/elupus/arcam_fmj/blob/5b03ef6705748177f4403c8dd3afc10077214a57/src/arcam/fmj/__init__.py#L393) and the mute list.

The decode modes (https://github.com/elupus/arcam_fmj/blob/5b03ef6705748177f4403c8dd3afc10077214a57/src/arcam/fmj/__init__.py#L281) should likely be just empty dicts.

**Comment by evanugarte** [comment]
Sounds good. I'll go about implementing this for the SA10/20/30 models.

**Comment by elupus** [comment]
So did this get resolved by those changes? Seems you marked it so. I did a new release so home assistant can get a version bump.

**Comment by evanugarte** [comment]
We now have support for sending the RC5 codes over, and my device responds to all of them except the power on for some reason.

How would you feel about building support for non-rc5 codes as mentioned [here](https://github.com/elupus/arcam_fmj/issues/4#issuecomment-902221070)? I can get started on that next since the SA models offer support.

**Comment by elupus** [comment]
Please do! I will need tests in place for this since it would be only way to verify it is not breaking.

**Comment by elupus** [comment]
Ps. Start with power since that is the crucial part.

**Comment by elupus** [comment]
Don't make it a parameter to set_source. Let the libe decide based on model.
